networks:
  firewalled-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24  # Nouveau sous-réseau pour éviter les conflits avec le bridge par défaut

services:
  firewall:
    build: ./firewall
    privileged: true
    cap_add:
      - NET_ADMIN
    networks:
      firewalled-net:
        ipv4_address: 172.18.0.100  # IP fixe pour le firewall

  server:
    build: ./server
    cap_add:
      - NET_ADMIN
    networks:
      firewalled-net:
        ipv4_address: 172.18.0.2  # IP fixe pour le serveur
    depends_on:
      - firewall
